### PR TITLE
Sample notebook

### LINKED ISSUE #1: Caching
I haven't yet added this to the README. I'm still going to need scachepy in my notebooks because I don't want to re-compute velocities and my stochastic kernel each time I have to re-generate a figure. I suggest we have a caching directory that mirrors the structure of the data directory. We won't share the actual cached files because they are too large but I will place `.gitkeep` files so that we have the same folder structure. What are your thoughts on this?

### PR DESCRIPTION
**Pull request by Marius1311**
This adds a skeleton notebook we will base our remaining notebooks on. 

@michalk8, please set up the paths. Once that's done, I can add a bit more meat to the skelleton notebook by running it with an actual AnnData object to see whether my proposed structure makes sense. 

closes #1 and #3

### CODE REVIEW

**Comment by michalk8** [comment]
@Marius1311 I've added my review on the ReviewNB, can you see it?

**Comment by Marius1311** [comment]
Hi Mike, yes I saw your comments, just went though them and commented again. 

Please, let's not make a science out of this. Can you just please push a commit where you make the changes you suggested (and that I agreed with in my comments)?

**Comment by michalk8** [comment]
@Marius1311 could you please check it out or quickly call me?

**Comment by michalk8** [comment]
I've run it with pancreas data and added the paths.py under the root.
I've also added cache/data to .gitignore so that we don't commit accidentally the data there.

**Comment by Marius1311** [comment]
Thanks Mike. Comments:
- the cache isn't used as intended. All pancreas notebook will share the same caching directory because they all use the same velocities. That's why I said the `cache` directly should mirror the `data` directly. For this reason, it does **not** make sense to define a "sample_notebook" caching directory, but this should just go into the "pancreas" caching directory. Nevertheless, **I think it's okay to leave this here** as it will prevent us from accidentally overwriting the cache when running the sample notebook. Just for the future, all pancreas notebooks should share one caching directory. 
- I don't think the way you added data and cache to the gitignore is ideal. This will ignore future changes to the folder sturcture, right? That's not what we want. We should rather add statements that ignore specific file extensions, but do still track the folder structure.

**Comment by Marius1311** [comment]
I'm currently running the notebook so please don't push atm, notebook merge conflicts are always nasty...

**Comment by michalk8** [comment]
Re example notebook: I know,  I was just testing this
Re gitignore: you're right - let's just ignore everything that is `.csv`, `.pickle` and `.h5ad`.

**Comment by Marius1311** [comment]
Awesome, I updated the `.gitignore`.

**Comment by Marius1311** [comment]
Hi Mike, I added also figure extensions to the gitignore because I don't think we should be comitting the actual figures, what do you think? Also, I added an example of how to save figures, using the `save_figure` global parameter. I know it's a bit convoluted but it's the best I could come up with. Is this okay for you? Furthermore, I added an example of how to cache the transition matrix. 

This is pretty much done and ready to be used from my point of view. I'm not yet 100% happy with the different pre-processing for the raw AnnData object, but this is a problem you only really encounter when you want to plot gene expression trends, so maybe not too relevant for your notebooks?

Let me know what you think, and whether we can merge and start.

**Comment by michalk8** [comment]
I think we can merge this.

**Comment by Marius1311** [comment]
Great. Will do.

**Pull request merged**
