### PR TITLE
Remove code of conduct from the README and delete unused folders

### PR DESCRIPTION
**Pull request by Marius1311**

### CODE REVIEW

**Comment by Marius1311** [comment]
Hi Mike, this deletes your symlinks - are they needed by the end-user?

**Comment by Marius1311** [comment]
Otherwise, this deletes some previously unused notebook folders and moves the conde of conduct in cellrank_notebooks_dev because it was only meant for us as a guideline when setting up this repo here.

**Comment by michalk8** [comment]
No the symlinks I've used only to test whether the plotting notebooks work on the data we have on the server.

**Comment by Marius1311** [comment]
ok, that means I can merge this?

**Comment by michalk8** [comment]
Yes, let's merge this.

**Comment by Marius1311** [comment]
thanks!

**Pull request merged**
